#!/usr/bin/env node

const fs = require("fs");
const readline = require("readline");

const allLinesStream = readline.createInterface({
	input: process.stdin
});

(async () => {
	for await (let line of allLinesStream) {
		console.log(JSON.parse(line));
	}
})();
