#!/usr/bin/env node

const fs = require("fs");

function main() {
	process.stdin.setEncoding("utf-8");
	process.stdin.on("data", function (data) {
		fs.appendFileSync("WAL.txt", data);
		const events = data.split("\n").filter((e) => e);
		for (let e of events) console.log(JSON.parse(e));
		console.log("*********************");
	});
}

main();
